services:
  db:
    image: timescale/timescaledb:latest-pg15 
    container_name: my-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lifo-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - lifo-net

volumes:
  pgdata:

networks:
  lifo-net:
    driver: bridge
